"""Emit the paper's tables and numeric macros as LaTeX from results/tables/.

Nothing numeric in paper/*.tex is typed by hand: every table row and every
number-carrying macro (\\headline, train/test sizes, seeds, crossovers) is
regenerated from the CSVs by this script, so re-running the experiments and
then this script updates the paper with no manual editing.

Formatting conventions (IEEE): booktabs rules, caption ABOVE the table, units
in the column header, three significant figures for real-valued cells.
"""

import math
import os

import pandas as pd

TABLES_IN = os.path.join("results", "tables")
TABLES_OUT = os.path.join("paper", "tables")
SECONDS_PER_HOUR = 3600
SIG_FIGS = 3


def sig(x, n=SIG_FIGS) -> str:
    """Round to n significant figures; integers past the decimal point are not padded."""
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "--"
    if x == 0:
        return "0"
    digits = n - int(math.floor(math.log10(abs(x)))) - 1
    rounded = round(x, digits)
    return f"{rounded:.{digits}f}" if digits > 0 else f"{int(rounded):d}"


def latex_escape(text: str) -> str:
    return text.replace("_", "\\_").replace("%", "\\%").replace("&", "\\&")


def write(name: str, body: str):
    os.makedirs(TABLES_OUT, exist_ok=True)
    path = os.path.join(TABLES_OUT, name)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("% AUTO-GENERATED by src/make_tables.py -- do not edit by hand.\n")
        handle.write(body)
    print(f"Wrote {path}")


def table_prediction():
    df = pd.read_csv(os.path.join(TABLES_IN, "prediction_metrics.csv"))
    rows = "\n".join(
        f"    {latex_escape(r.predictor)} & {sig(r.mae)} & {sig(r.rmse)} & {sig(100 * r.under_prediction_rate)} \\\\"
        for r in df.itertuples()
    )
    body = f"""\\begin{{table}}[t]
  \\caption{{Prediction error on the chronological test set. The under-prediction rate is the fraction of test tasks whose predicted runtime is below the actual runtime.}}
  \\label{{tab:prediction}}
  \\centering
  \\begin{{tabular}}{{lrrr}}
    \\toprule
    Predictor & MAE (s) & RMSE (s) & Under-prediction (\\%) \\\\
    \\midrule
{rows}
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
"""
    write("table_prediction.tex", body)


def table_schedulers():
    df = pd.read_csv(os.path.join(TABLES_IN, "scheduler_comparison.csv"))
    rows = "\n".join(
        f"    {latex_escape(r.scheduler)} & {sig(r.avg_waiting_time / SECONDS_PER_HOUR)} & "
        f"{sig(r.avg_turnaround_time / SECONDS_PER_HOUR)} & {sig(r.avg_response_time / SECONDS_PER_HOUR)} & "
        f"{int(r.context_switches):,} \\\\"
        for r in df.itertuples()
    )
    body = f"""\\begin{{table}}[t]
  \\caption{{Scheduling outcomes on the chronological test set. Times are averages per task.}}
  \\label{{tab:schedulers}}
  \\centering
  \\begin{{tabular}}{{lrrrr}}
    \\toprule
    Scheduler & Waiting (h) & Turnaround (h) & Response (h) & Context switches \\\\
    \\midrule
{rows}
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
"""
    write("table_schedulers.tex", body)


def table_sensitivity():
    uniform = pd.read_csv(os.path.join(TABLES_IN, "sensitivity.csv"))
    lognormal = pd.read_csv(os.path.join(TABLES_IN, "sensitivity_lognormal.csv"))

    def block(df, level_symbol):
        return "\n".join(
            f"    {level_symbol} = {r.level:g} & {sig(r.avg_waiting_time / SECONDS_PER_HOUR)} \\\\"
            for r in df.itertuples()
        )

    body = f"""\\begin{{table}}[t]
  \\caption{{Sensitivity of SRTF to injected prediction error. Predictions are the true runtime perturbed by the stated noise model, floored at 1\\,s. Average waiting time is per task.}}
  \\label{{tab:sensitivity}}
  \\centering
  \\begin{{tabular}}{{lr}}
    \\toprule
    Injected error level & Waiting (h) \\\\
    \\midrule
    \\multicolumn{{2}}{{l}}{{\\textit{{Bounded uniform: }} $\\hat{{t}} = t\\,(1 + U(-\\varepsilon, \\varepsilon))$}} \\\\
{block(uniform, "$\\varepsilon$")}
    \\midrule
    \\multicolumn{{2}}{{l}}{{\\textit{{Log-normal: }} $\\hat{{t}} = t \\exp(\\sigma Z),\\; Z \\sim \\mathcal{{N}}(0,1)$}} \\\\
{block(lognormal, "$\\sigma$")}
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
"""
    write("table_sensitivity.tex", body)


def macros():
    comparison = pd.read_csv(os.path.join(TABLES_IN, "scheduler_comparison.csv")).set_index("scheduler")["avg_waiting_time"]
    summary = pd.read_csv(os.path.join(TABLES_IN, "run_summary.csv")).set_index("key")["value"]

    # Same formula as src/experiments.py, recomputed here from the CSV so that
    # editing the CSV (or re-running experiments) is the single source of truth.
    w_expavg, w_gbm, w_oracle = comparison["SRTF+ExpAvg"], comparison["SRTF+GBM"], comparison["SRTF+Oracle"]
    recovery = (w_expavg - w_gbm) / (w_expavg - w_oracle) * 100

    def level_macro(value):
        return "not reached" if math.isnan(value) else f"{value:g}"

    lines = [
        f"\\newcommand{{\\headline}}{{{recovery:.1f}\\%}}",
        f"\\newcommand{{\\nTasks}}{{{int(summary['n_tasks']):,}}}",
        f"\\newcommand{{\\nTrainTasks}}{{{int(summary['n_train']):,}}}",
        f"\\newcommand{{\\nTestTasks}}{{{int(summary['n_test']):,}}}",
        f"\\newcommand{{\\trainPercent}}{{{int(round(100 * summary['train_fraction']))}}}",
        f"\\newcommand{{\\seedValue}}{{{int(summary['seed'])}}}",
        f"\\newcommand{{\\quantumValue}}{{{int(summary['quantum'])}}}",
        f"\\newcommand{{\\crossoverUniform}}{{{level_macro(summary['crossover_uniform'])}}}",
        f"\\newcommand{{\\crossoverLognormal}}{{{level_macro(summary['crossover_lognormal'])}}}",
        f"\\newcommand{{\\sigmaLinear}}{{{summary['sigma_linear']:.2f}}}",
        f"\\newcommand{{\\sigmaGBM}}{{{summary['sigma_gbm']:.2f}}}",
    ]
    write("macros.tex", "\n".join(lines) + "\n")


def main():
    table_prediction()
    table_schedulers()
    table_sensitivity()
    macros()


if __name__ == "__main__":
    main()
